# Generated by Django 3.2.22 on 2024-06-16 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='order_status',
            field=models.BooleanField(default=False),
        ),
    ]
